
IF OBJECT_ID('[#schema#].[#TableName#]') IS NOT NULL
BEGIN
	DROP TABLE [#schema#].[#TableName#]
END

IF OBJECT_ID('[#schema#].[#TableName#]') IS NULL
BEGIN
CREATE TABLE [#schema#].[#TableName#](
#columns#
 CONSTRAINT [PK_#TableName#] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

#indexes#

END